### ISSUE TITLE
issues with ng-show?

### ISSUE THREAD

**Issue by Ir1sh** [fergaldoyle/angular.js-ie8-builds#5]
Have you guys noticed any issues with ng-show working in ie8? I cant get it to work without overriding the default style as described int he angular source here

By default, the `.ng-hide` class will style the element with `display: none!important`. If you wish to change
 the hide behavior with ngShow/ngHide then this can be achieved by restating the styles for the `.ng-hide`
 class in CSS:
 
  ```css
  .ng-hide {
    /&#42; this is just another form of hiding an element &#42;/
    display: block!important;
    position: absolute;
    top: -9999px;
    left: -9999px;
  }
  ```
not sure if and how this will effect animations, looking into it now
